"""fix table

Revision ID: db31226e62b5
Revises: 
Create Date: 2023-05-18 15:38:49.760890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db31226e62b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingridient_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('inventories_ingrdient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredients', ['ingridient_id'], ['id'])
        batch_op.drop_column('ingrdient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingrdient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventories_ingrdient_id_fkey', 'ingredients', ['ingrdient_id'], ['id'])
        batch_op.drop_column('ingridient_id')

    # ### end Alembic commands ###
